# .github/workflows/tf-valriable.yml

name: '[TEST] TF Variable'

on:
  workflow_dispatch:

jobs:
  variable:
    name: 'Variable Manipulation'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Manual DIR set
      #   run: |
      #     FILES='examples/fabric_project/variables.tf'
      #     export DIR="$(dirname "${FILES}")"
      #     echo "${DIR}"
      #     echo "ENV_DIR=${DIR}" >> $GITHUB_ENV

      - name: Get added and modified files
        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '["examples/fabric_project/variables.tf","examples/fabric_project/main.tf"]')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "File Added/Modified : ${added_modified_file}" 
          done
          # echo "${added_modified_files[0]}"
          DIR="$(dirname ${added_modified_files[0]})"
          # echo "DIR=${DIR:2}"
          echo "ENV_DIR=${DIR:2}" >> $GITHUB_ENV

      - name: Print ENV_DIR
        run: |
          echo "${ENV_DIR}"