# .github/workflows/tf-plan.yml

name: '[NEW] BUILD - Terraform Plan'

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'examples/**/*.tf'
  workflow_dispatch:
    inputs:
      PRNumber:
        description: 'PR #'     
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.0.11

      - name: Set environment
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/.github/workflows/fake-key.json" >> $GITHUB_ENV
          echo $GOOGLE_APPLICATION_CREDENTIALS # This will print the file path in GOOGLE_APPLICATION_CREDENTIALS variable
          # cat $GOOGLE_APPLICATION_CREDENTIALS # This will print the file content

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: tools

      - name: execute py script (auto) # run the tf-plan.py
        id: tf-plan-auto
        if: github.event_name == 'pull_request'
        run: |
          python tf-plan.py ${{ github.event.number }}
        working-directory: tools

      - name: execute py script (manual) # run the tf-plan.py
        id: tf-plan-manual
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ github.event.inputs.PRNumber }}" =~ ^[0-9]+$ ]]
          then
            python tf-plan.py ${{ github.event.inputs.PRNumber }}
          else
            echo "INVALID PR Number ENTERED..."
            exit 1
          fi
        working-directory: tools